version: '3'

services:
  postgres:
    image: 'postgis/postgis'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: 'sandbox'
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5433:5432'
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
