\qecho '---------- Schema setup ------------'
create schema if not exists test_update_triggers;
set search_path to test_update_triggers;

DROP TABLE IF EXISTS table_a;
DROP TABLE IF EXISTS table_b;

CREATE TABLE IF NOT EXISTS table_a (
  id INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
  int_val INT
);

CREATE TABLE IF NOT EXISTS table_b (
  id INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
  int_val INT
);

INSERT INTO table_a (int_val)
  SELECT * FROM generate_series(1, 100000000);

INSERT INTO table_b (int_val)
  SELECT * FROM generate_series(50000000, 150000000);

SELECT COUNT(*) FROM table_a;
SELECT COUNT(*) FROM table_b;

explain SELECT * FROM (
  SELECT * FROM table_a
  UNION ALL
  SELECT * FROM table_b
) AS subquery
WHERE int_val > 50000000 AND int_val < 100000000
