\qecho '---------- Schema setup ------------'

CREATE SCHEMA IF NOT EXISTS test_events_to_state_snapshots;
SET search_path TO test_events_to_state_snapshots;

DROP TABLE IF EXISTS events;
CREATE TABLE events (
  id INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL,
  type text NOT NULL
);

DROP TABLE IF EXISTS calls;
CREATE TABLE IF NOT EXISTS calls (
  id INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL
);

INSERT INTO events (created_at, type) VALUES
  ('2019-01-01', 'created'),
  ('2019-01-10', 'add_hot_status'),
  ('2019-01-20', 'convert_to_prospect'),
  ('2019-02-01', 'add_quoted_status'),
  ('2019-02-10', 'convert_to_customer');

INSERT INTO calls (created_at) VALUES
  -- created: 1
  ('2019-01-05'),
  -- add_hot_status: 1
  ('2019-01-15'),
  -- convert_to_prospect: 1
  ('2019-01-25'),
  -- add_quoted_status: 3
  ('2019-02-05'), ('2019-02-06'), ('2019-02-07'),
  -- convert_to_prospect: 2
  ('2019-02-15'), ('2019-02-16');

/* SELECT * FROM ( */
  SELECT
    events.created_at AS event_date,
    calls.created_at AS call_date,
    events.type AS event_type,
    ROW_NUMBER() OVER(PARTITION BY events.type ORDER BY calls.created_at DESC, events.created_at DESC) = 1 AS is_last_state
  FROM calls
  LEFT JOIN events ON calls.created_at > events.created_at
/* ) AS subquery */
/* WHERE is_last_state */





















