\qecho '---------- Schema setup ------------'

create schema if not exists test_updatable_views;
set search_path to test_updatable_views;
/* --set schema test_updatable_views; */

drop view if exists tasks_with_users;
drop table if exists tasks;
drop table if exists users;

create table if not exists users (
  id int generated by default as identity primary key,
  name text
);

create table if not exists tasks (
  id int generated by default as identity primary key,
  user_id int references users(id),
  name text
);

create or replace view tasks_with_users as (
  select
    tasks.id as task_id,
    tasks.name as task_name,
    users.id as user_id,
    users.name as user_name
  from tasks
  left join users on tasks.user_id = users.id
);

insert into users (name) values ('john'), ('andrew');
insert into tasks (user_id, name) values
  (1, 'first john task'),
  (1, 'second john task');
insert into tasks (user_id, name) values
  (2, 'first andrew task'),
  (2, 'second andrew task');

select * from users;
select * from tasks;
select * from tasks_with_users;

update tasks_with_users
  set user_name = 'new john'
  where task_id = 1
  and user_id = 1;

select * from users;
select * from tasks;
select * from tasks_with_users;
